# Generated by Django 3.2.6 on 2021-08-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_city_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country_code',
        ),
    ]
