# Generated by Django 3.2.6 on 2021-08-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_remove_city_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country_code',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
