# Generated by Django 3.2.6 on 2021-08-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_city_country_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='namef',
        ),
    ]
