# Generated by Django 3.2.6 on 2021-08-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_rename_name_city_namef'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='namef',
            new_name='name',
        ),
    ]
