# Generated by Django 3.2.6 on 2021-08-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_rename_namef_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='temperature',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=30),
        ),
    ]
